// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.707
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func NewGroup() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"flex justify-center items-center py-3\"><form class=\"flex flex-col justify-center items-center\" hx-post=\"/new_group\" hx-target-error=\"#feedback\" hx-indicator=\"#indicator\"><div class=\"flex flex-col py-5 text-3xl\">Create New Group</div><div class=\"w-full\"><div class=\"label\"><label class=\"label-text\">Group Name</label></div><input type=\"text\" id=\"groupname\" name=\"groupname\" class=\"grow input input-bordered flex items-center w-full\" placeholder=\"ie: My Group\"></div><div class=\"w-full\"><div class=\"label\"><label class=\"label-text\">Group Description</label></div><input type=\"text\" id=\"description\" name=\"description\" class=\"grow input input-bordered flex items-center w-full\" placeholder=\"Description (optional)\"></div><div class=\"w-full\"><div class=\"label\"><label class=\"label-text\">Main Currency</label></div><input type=\"text\" id=\"currency\" name=\"currency\" class=\"grow input input-bordered flex items-center w-full\" placeholder=\"USD\"></div><div class=\"w-full py-5\"><button type=\"submit\" class=\"btn btn-active btn-neutral btn-wide text-lg font-light\">Create Group</button></div><div id=\"indicator\" class=\"htmx-indicator\"><div class=\"flex justify-center items-center w-full\"><span class=\"loading loading-spinner loading-md\"></span></div></div><div id=\"feedback\"></div></form></div><div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
