ALTER TABLE users ALTER COLUMN id DROP DEFAULT;
ALTER TABLE expense ALTER COLUMN id DROP DEFAULT;
ALTER TABLE expense_type ALTER COLUMN id DROP DEFAULT;
ALTER TABLE group_member ALTER COLUMN id DROP DEFAULT;
ALTER TABLE groups ALTER COLUMN id DROP DEFAULT;
ALTER TABLE item ALTER COLUMN id DROP DEFAULT;
ALTER TABLE ledger ALTER COLUMN id DROP DEFAULT;