CREATE TABLE IF NOT EXISTS users(
    "ID" UUID NOT NULL PRIMARY KEY,
    "USERNAME" VARCHAR(32) NOT NULL,
    "FIRSTNAME" VARCHAR(32) NOT NULL,
    "LASTNAME" VARCHAR(32) NOT NULL,
    "PASSWORD_HASH" VARCHAR(256) NOT NULL,
    "EXTERNAL_TYPE" VARCHAR(16),
    "EXTERNAL_ID" VARCHAR(64),
    "CREATE_TIME" TIMESTAMP WITH TIME ZONE NOT NULL,
    "IS_ACTIVE" BOOLEAN NOT NULL
);