SERVERFUL_ROOT="${SERVERFUL_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"
REPO_ROOT="${REPO_ROOT:-$(cd "$SERVERFUL_ROOT/../../.." && pwd)}"

TF_DIR="${TF_DIR:-$SERVERFUL_ROOT/tf}"
TF_VARS_FILE="${TF_VARS_FILE:-terraform.tfvars}"
APP_DIR="${APP_DIR:-/opt/expense-tracker}"
BACKEND_ENV_PATH="${BACKEND_ENV_PATH:-/etc/expense-tracker/backend.env}"
BACKEND_URL="${BACKEND_URL:-127.0.0.1:8080}"
SYSTEMD_SERVICE_NAME="${SYSTEMD_SERVICE_NAME:-expense-tracker}"
BUILD_ROOT="${BUILD_ROOT:-$REPO_ROOT/deployment/.build/deploy}"
ARTIFACT_KEY="${ARTIFACT_KEY:-expense-tracker/backend-release.tar.gz}"
EDGE_ARTIFACT_KEY="${EDGE_ARTIFACT_KEY:-expense-tracker/edge-release.tar.gz}"
API_HTTP_HEALTHCHECK_URL="${API_HTTP_HEALTHCHECK_URL:-}"
API_HTTPS_HEALTHCHECK_URL="${API_HTTPS_HEALTHCHECK_URL:-}"
